import type { User, Driver, Order, MenuItem, Promotion, Review } from './types';

export const users: User[] = [
  {
    id: 'usr_1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    avatarUrl: 'https://picsum.photos/seed/user1/100/100',
    dataAiHint: 'person portrait',
    dateJoined: '2023-01-15',
    lastOrder: '2024-05-20',
    status: 'Active',
    address: '123 Maple Street, Springfield',
    favorites: 5,
    promoCodes: 2,
    supportTickets: 1,
    activitySummary: "Frequent user, orders 3-4 times a week. Primarily orders Italian and Mexican food. Recently left a 2-star review citing late delivery."
  },
  {
    id: 'usr_2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    avatarUrl: 'https://picsum.photos/seed/user2/100/100',
    dataAiHint: 'person portrait',
    dateJoined: '2023-03-22',
    lastOrder: '2024-05-18',
    status: 'Active',
    address: '456 Oak Avenue, Springfield',
    favorites: 2,
    promoCodes: 0,
    supportTickets: 0,
    activitySummary: "Has used multiple accounts to abuse new user promotions. Reported by two drivers for inappropriate language in delivery notes."
  },
  {
    id: 'usr_3',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    avatarUrl: 'https://picsum.photos/seed/user3/100/100',
    dataAiHint: 'person portrait',
    dateJoined: '2023-05-30',
    lastOrder: '2024-05-21',
    status: 'Blocked',
    address: '789 Pine Lane, Springfield',
    favorites: 10,
    promoCodes: 5,
    supportTickets: 3,
    activitySummary: "Account was blocked due to repeated chargeback fraud and harassment of support staff."
  },
];

export const drivers: Driver[] = [
  {
    id: 'drv_1',
    name: 'David Green',
    email: 'david@example.com',
    avatarUrl: 'https://picsum.photos/seed/driver1/100/100',
    dataAiHint: 'person portrait',
    phone: '555-1234',
    vehicle: 'Toyota Prius',
    dateJoined: '2022-11-01',
    status: 'Approved',
    availability: 'Online',
  },
  {
    id: 'drv_2',
    name: 'Eve Williams',
    email: 'eve@example.com',
    avatarUrl: 'https://picsum.photos/seed/driver2/100/100',
    dataAiHint: 'person portrait',
    phone: '555-5678',
    vehicle: 'Honda Civic',
    dateJoined: '2023-02-10',
    status: 'Approved',
    availability: 'Offline',
  },
  {
    id: 'drv_3',
    name: 'Frank Miller',
    email: 'frank@example.com',
    avatarUrl: 'https://picsum.photos/seed/driver3/100/100',
    dataAiHint: 'person portrait',
    phone: '555-8765',
    vehicle: 'Ford Focus',
    dateJoined: '2024-05-01',
    status: 'Pending',
    availability: 'Offline',
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-001',
    customer: { name: 'Alice Johnson', avatarUrl: 'https://picsum.photos/seed/user1/100/100', dataAiHint: 'person portrait' },
    driver: { name: 'David Green', avatarUrl: 'https://picsum.photos/seed/driver1/100/100', dataAiHint: 'person portrait' },
    items: [{ name: 'Margherita Pizza', quantity: 1 }, { name: 'Coke', quantity: 2 }],
    status: 'Delivered',
    total: 25.50,
    date: '2024-05-28T14:48:00',
    deliveryAddress: '123 Maple Street, Springfield',
  },
  {
    id: 'ORD-002',
    customer: { name: 'Bob Smith', avatarUrl: 'https://picsum.photos/seed/user2/100/100', dataAiHint: 'person portrait' },
    driver: { name: 'David Green', avatarUrl: 'https://picsum.photos/seed/driver1/100/100', dataAiHint: 'person portrait' },
    items: [{ name: 'Cheeseburger', quantity: 2 }],
    status: 'On The Way',
    total: 30.00,
    date: '2024-05-28T18:30:00',
    deliveryAddress: '456 Oak Avenue, Springfield',
  },
  {
    id: 'ORD-003',
    customer: { name: 'Charlie Brown', avatarUrl: 'https://picsum.photos/seed/user3/100/100', dataAiHint: 'person portrait' },
    items: [{ name: 'Caesar Salad', quantity: 1 }],
    status: 'Preparing',
    total: 15.75,
    date: '2024-05-28T19:00:00',
    deliveryAddress: '789 Pine Lane, Springfield',
  },
  {
    id: 'ORD-004',
    customer: { name: 'Alice Johnson', avatarUrl: 'https://picsum.photos/seed/user1/100/100', dataAiHint: 'person portrait' },
    items: [{ name: 'Spaghetti Carbonara', quantity: 1 }],
    status: 'Pending',
    total: 18.00,
    date: '2024-05-28T19:15:00',
    deliveryAddress: '123 Maple Street, Springfield',
  },
  {
    id: 'ORD-005',
    customer: { name: 'Bob Smith', avatarUrl: 'https://picsum.photos/seed/user2/100/100', dataAiHint: 'person portrait' },
    items: [{ name: 'Margherita Pizza', quantity: 1 }],
    status: 'Cancelled',
    total: 22.00,
    date: '2024-05-27T12:00:00',
    deliveryAddress: '456 Oak Avenue, Springfield',
  },
];

export const menuItems: MenuItem[] = [
  {
    id: 'item-1',
    name: 'Margherita Pizza',
    category: 'Pizza',
    price: 18.00,
    imageUrl: 'https://picsum.photos/seed/pizza1/400/300',
    dataAiHint: 'pizza food',
    description: 'Classic pizza with fresh mozzarella, tomatoes, and basil.',
    options: [{name: 'Gluten-free crust', price: 3.00}],
    addons: [{name: 'Extra cheese', price: 2.00}, {name: 'Mushrooms', price: 1.50}],
  },
  {
    id: 'item-2',
    name: 'Cheeseburger',
    category: 'Burgers',
    price: 15.50,
    imageUrl: 'https://picsum.photos/seed/burger1/400/300',
    dataAiHint: 'burger food',
    description: 'Juicy beef patty with cheddar cheese, lettuce, tomato, and onion.',
    options: [{name: 'Double patty', price: 4.00}],
    addons: [{name: 'Bacon', price: 2.50}, {name: 'Avocado', price: 2.00}],
  },
  {
    id: 'item-3',
    name: 'Caesar Salad',
    category: 'Salads',
    price: 12.00,
    imageUrl: 'https://picsum.photos/seed/salad1/400/300',
    dataAiHint: 'salad food',
    description: 'Crisp romaine lettuce with Caesar dressing, croutons, and parmesan.',
    options: [],
    addons: [{name: 'Grilled chicken', price: 4.00}, {name: 'Shrimp', price: 6.00}],
  },
  {
    id: 'item-4',
    name: 'Spaghetti Carbonara',
    category: 'Pasta',
    price: 22.50,
    imageUrl: 'https://picsum.photos/seed/pasta1/400/300',
    dataAiHint: 'pasta food',
    description: 'Pasta with a creamy egg sauce, pancetta, and pecorino cheese.',
    options: [],
    addons: [],
  },
  {
    id: 'item-5',
    name: 'Chocolate Brownie',
    category: 'Desserts',
    price: 8.00,
    imageUrl: 'https://picsum.photos/seed/dessert1/400/300',
    dataAiHint: 'dessert food',
    description: 'Warm chocolate brownie with a scoop of vanilla ice cream.',
    options: [],
    addons: [{name: 'Caramel sauce', price: 1.00}],
  },
];

export const promotions: Promotion[] = [
  {
    id: 'promo-1',
    code: 'WEEKEND20',
    description: '20% off on all orders over $50 during weekends.',
    discount: '20%',
    status: 'Active',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
  },
  {
    id: 'promo-2',
    code: 'FREEDELIVERY',
    description: 'Free delivery on your first order.',
    discount: '100% Delivery',
    status: 'Active',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
  },
  {
    id: 'promo-3',
    code: 'LUNCHDEAL',
    description: '15% off on all lunch orders between 11am and 2pm.',
    discount: '15%',
    status: 'Expired',
    startDate: '2023-11-01',
    endDate: '2023-11-30',
  },
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    customerName: 'Alice Johnson',
    rating: 4,
    comment: 'The pizza was delicious, but the delivery was 15 minutes late. The driver was very apologetic though.',
    date: '2024-05-20',
  },
  {
    id: 'rev-2',
    customerName: 'Bob Smith',
    rating: 2,
    comment: 'My burger was cold and the fries were soggy. What a damn waste of money. Never ordering from here again.',
    date: '2024-05-18',
  },
  {
    id: 'rev-3',
    customerName: 'Charlie Brown',
    rating: 5,
    comment: 'Absolutely amazing! The carbonara tasted authentic, just like in Italy. Highly recommend!',
    date: '2024-05-21',
  },
  {
    id: 'rev-4',
    customerName: 'Diana Prince',
    rating: 1,
    comment: 'This is the worst service ever! My order was completely wrong and the support team was useless. I want my money back, this is complete bullshit.',
    date: '2024-05-19',
  },
];
